#!/usr/bin/env node
// Reads YAML frontmatter from every <specsDir>/<id>/requirements.md and
// regenerates BACKLOG.md (path from agent-harness.config.json
// workflow.backlog) in a compact format designed to be cheap when read by
// an agent: one line per ticket, fixed positions, symbolic status.
//
// Usage:
//   node tools/qa/generate-backlog.mjs                  # write BACKLOG.md (active tickets)
//   node tools/qa/generate-backlog.mjs --check          # exit non-zero if BACKLOG.md drifts
//   node tools/qa/generate-backlog.mjs --include-done   # also write BACKLOG-archive.md
//
// Required frontmatter per requirements.md: id, title, status, owner,
// priority. Optional: depends_on (list).
//
// Status flow: Planned → Draft → Approved → In progress → Done.
// `Blocked` is available at any active stage.

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { HARNESS_PATHS } from "./harness-paths.mjs";

const CONFIG_FILE = HARNESS_PATHS.config;
const TEMPLATE_DIR = "_template";
const STATUS_ORDER = ["In progress", "Blocked", "Approved", "Draft", "Planned", "Done"];
const REQUIRED_FIELDS = ["id", "title", "status", "owner", "priority"];

// Compact symbolic status. Single character per ticket.
const STATUS_SYMBOL = {
  "In progress": ">",
  Blocked: "?",
  Approved: "*",
  Draft: "=",
  Planned: ".",
  Done: "#"
};

function readConfig() {
  if (!existsSync(CONFIG_FILE)) {
    console.error(`generate-backlog: missing ${CONFIG_FILE}`);
    process.exit(1);
  }
  const config = JSON.parse(readFileSync(CONFIG_FILE, "utf8"));
  if (config.workflow?.mode === "none" || !config.workflow?.specsDir || !config.workflow?.backlog) {
    console.error("generate-backlog: workflow.mode is none or workflow.specsDir/backlog missing in manifest");
    process.exit(1);
  }
  return {
    specsDir: config.workflow.specsDir,
    backlogPath: config.workflow.backlog,
    archivePath: join(dirname(config.workflow.backlog), "BACKLOG-archive.md")
  };
}

function parseFrontmatter(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---/);
  if (!m) return null;
  const fm = {};
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^([a-zA-Z_]+):\s*(.*)$/);
    if (!kv) continue;
    let val = kv[2].trim();
    if (val.startsWith("[") && val.endsWith("]")) {
      val = val
        .slice(1, -1)
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
    } else if (val === "null" || val === "") {
      val = null;
    }
    fm[kv[1]] = val;
  }
  return fm;
}

function readSpecs(specsDir) {
  if (!existsSync(specsDir)) return [];
  const dirs = readdirSync(specsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name !== TEMPLATE_DIR);
  const specs = [];
  const errors = [];
  for (const d of dirs) {
    const reqPath = join(specsDir, d.name, "requirements.md");
    // Quietly skip dirs that don't have requirements.md — they're scaffolding
    // (e.g. a ticketsDir README parent) rather than real specs. Real spec
    // dirs always have requirements.md per the workflow contract.
    if (!existsSync(reqPath)) continue;
    const fm = parseFrontmatter(readFileSync(reqPath, "utf8"));
    if (!fm) {
      errors.push(`${reqPath}: no YAML frontmatter (must start with --- ... ---)`);
      continue;
    }
    for (const field of REQUIRED_FIELDS) {
      if (!(field in fm) || fm[field] === null || fm[field] === "") {
        errors.push(`${reqPath}: missing required frontmatter field "${field}"`);
      }
    }
    if (fm.status && !STATUS_ORDER.includes(fm.status)) {
      errors.push(
        `${reqPath}: status "${fm.status}" not in allowed set (${STATUS_ORDER.join(", ")})`
      );
    }
    specs.push({ ...fm, dir: d.name, path: reqPath });
  }
  if (errors.length > 0) {
    for (const e of errors) console.error(`  - ${e}`);
    throw new Error(`backlog: ${errors.length} frontmatter error(s)`);
  }
  return specs;
}

function sortSpecs(specs) {
  return specs.slice().sort((a, b) => {
    const sa = STATUS_ORDER.indexOf(a.status);
    const sb = STATUS_ORDER.indexOf(b.status);
    if (sa !== sb) return sa - sb;
    return (a.priority || "P9").localeCompare(b.priority || "P9");
  });
}

function renderCompactRow(s) {
  const symbol = STATUS_SYMBOL[s.status] ?? "?";
  const owner = s.owner || "-";
  const deps = Array.isArray(s.depends_on) && s.depends_on.length > 0 ? s.depends_on.join(",") : "-";
  return `${s.id} ${s.priority} ${symbol} ${owner} ${deps} ${s.title}`;
}

function renderHeader() {
  return [
    "<!-- AUTO-GENERATED by tools/qa/generate-backlog.mjs — do not edit by hand. -->",
    "<!-- Source of truth: YAML frontmatter on each <specsDir>/<id>/requirements.md. -->",
    "<!-- Regenerate: npm run backlog:generate. Compact format — keep it small. -->",
    "<!-- Format: ID prio status owner deps title -->",
    "<!-- Status: > in_progress  ? blocked  * approved  = draft  . planned  # done -->",
    ""
  ].join("\n");
}

function renderBacklog(specs) {
  const active = sortSpecs(specs.filter((s) => s.status !== "Done"));
  const lines = [renderHeader()];
  lines.push(`# Backlog (${active.length} active)`);
  lines.push("");
  lines.push("To pick up a ticket: set its requirements.md frontmatter status to `In progress`,");
  lines.push("set owner to your handle, run `npm run backlog:generate`, commit. See AGENTS.md.");
  lines.push("");
  for (const s of active) lines.push(renderCompactRow(s));
  lines.push("");
  return lines.join("\n");
}

function renderArchive(specs) {
  const done = sortSpecs(specs.filter((s) => s.status === "Done"));
  const lines = [renderHeader()];
  lines.push(`# Backlog Archive (${done.length} done)`);
  lines.push("");
  lines.push("Closed tickets. Generated only on `--include-done`. Read on demand only.");
  lines.push("");
  for (const s of done) lines.push(renderCompactRow(s));
  lines.push("");
  return lines.join("\n");
}

function main() {
  const { specsDir, backlogPath, archivePath } = readConfig();
  const checkMode = process.argv.includes("--check");
  const includeDone = process.argv.includes("--include-done");
  const specs = readSpecs(specsDir);
  const generated = renderBacklog(specs);
  if (checkMode) {
    if (!existsSync(backlogPath)) {
      console.error(`${backlogPath} missing. Run 'npm run backlog:generate'.`);
      process.exit(1);
    }
    const onDisk = readFileSync(backlogPath, "utf8");
    if (onDisk !== generated) {
      console.error(`${backlogPath} drifted. Run 'npm run backlog:generate' to regenerate.`);
      process.exit(1);
    }
    console.log("backlog check passed");
    return;
  }
  writeFileSync(backlogPath, generated);
  const active = specs.filter((s) => s.status !== "Done").length;
  console.log(`wrote ${backlogPath} (${active} active ticket${active === 1 ? "" : "s"})`);
  if (includeDone) {
    writeFileSync(archivePath, renderArchive(specs));
    const done = specs.filter((s) => s.status === "Done").length;
    console.log(`wrote ${archivePath} (${done} done ticket${done === 1 ? "" : "s"})`);
  }
}

main();
